---

version: "3"

services:
  traefik:
    image: chaosdorf/ingress
    build: .
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
